// examples/vue/IbanChecker.vue
<!-- Vue 3 (<script setup>) — vérificateur d'IBAN / RIB UEMOA -->
<script setup lang="ts">
import { ref } from "vue";
import { identifyBank, type ResolveResult } from "uemoa-bank-resolver";

const iban = ref("");
const result = ref<ResolveResult | null>(null);

function check() {
  result.value = identifyBank(iban.value);
}
</script>

<template>
  <form aria-label="Vérification d'IBAN UEMOA" @submit.prevent="check">
    <label for="iban">IBAN ou RIB</label>
    <input
      id="iban"
      v-model="iban"
      placeholder="CI93 CI034 01049 142643500018 09"
      autocomplete="off"
      spellcheck="false"
    />
    <button type="submit">Identifier la banque</button>

    <output v-if="result && result.valid">
      <strong>{{ result.bank?.name ?? "Banque inconnue" }}</strong>
      <p>
        {{ result.country }} · code banque {{ result.parts?.bankCode }} ·
        guichet {{ result.parts?.branchCode }}
      </p>
    </output>

    <p v-else-if="result" role="alert">
      {{ result.errors[0] ?? "IBAN invalide" }}
    </p>
  </form>
</template>

// examples/react/IbanChecker.tsx
// React — vérificateur d'IBAN / RIB UEMOA
// Le package est du JS pur : il s'exécute aussi bien côté client que serveur.
import { useState } from "react";
import { identifyBank, type ResolveResult } from "uemoa-bank-resolver";

export function IbanChecker() {
  const [iban, setIban] = useState("");
  const [result, setResult] = useState<ResolveResult | null>(null);

  function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    setResult(identifyBank(iban));
  }

  return (
    <form onSubmit={handleSubmit} aria-label="Vérification d'IBAN UEMOA">
      <label htmlFor="iban">IBAN ou RIB</label>
      <input
        id="iban"
        value={iban}
        onChange={(e) => setIban(e.target.value)}
        placeholder="CI93 CI034 01049 142643500018 09"
        autoComplete="off"
        spellCheck={false}
      />
      <button type="submit">Identifier la banque</button>

      {result && result.valid && (
        <output>
          <strong>{result.bank?.name ?? "Banque inconnue"}</strong>
          <p>
            {result.country} · code banque {result.parts?.bankCode} · guichet{" "}
            {result.parts?.branchCode}
          </p>
        </output>
      )}

      {result && !result.valid && (
        <p role="alert">{result.errors[0] ?? "IBAN invalide"}</p>
      )}
    </form>
  );
}
